AWS_REGION         = "eu-west-1"
AWS_PROFILE        = "__MY_LOCAL_AWS_PROFILE_NAME__"
environment        = "Development"
datadog_secrets_id = "__AWS_SECRETMANAGER_ARN__"
slack_channel      = "@slack-dev-mon"
service_region     = "us-east-2"